apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: renovate-secrets
  namespace: flux-system
spec:
  interval: 1h
  retryInterval: 1m
  timeout: 5m
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./apps/renovate/secrets
  prune: true
  healthCheckExprs:
    - apiVersion: external-secrets.io/v1beta1
      kind: ExternalSecret
      failed: status.conditions.filter(e, e.type == 'Ready').all(e, e.status == 'False')
      current: status.conditions.filter(e, e.type == 'Ready').all(e, e.status == 'True')
#---
#apiVersion: kustomize.toolkit.fluxcd.io/v1
#kind: Kustomization
#metadata:
#  name: renovate-system
#  namespace: flux-system
#spec:
#  dependsOn:
#    - name: renovate-secrets
#  interval: 1h
#  retryInterval: 1m
#  timeout: 5m
#  sourceRef:
#    kind: GitRepository
#    name: flux-system
#  path: ./apps/renovate/controller
#  prune: true
