apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: headlamp
resources:
  - helmrepository.yml
  - helmrelease.yml
  - httproute.yml

configMapGenerator:
  - name: headlamp-config
    files:
      - values.yaml=values.yml

configurations:
  - kustomizeconfig.yml
