apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: envoygateway
resources:
  - namespace.yml
  - ocirepository.yml
  - helmrelease.yml

#configMapGenerator:
#  - name: envoy-values
#    files:
#      - values.yaml=values.yml
#
#configurations:
#  - kustomizeconfig.yml
