apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: reflector-system
  namespace: flux-system
spec:
  interval: 1h
  retryInterval: 1m
  timeout: 5m
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./infrastructure/reflector/controller
  prune: true
#  healthChecks:
#  - apiVersion: apps/v1
#    kind: Deployment
#    name: clustersecret-cluster-secret-clustersecret
#    namespace: clustersecret
#---
#apiVersion: kustomize.toolkit.fluxcd.io/v1
#kind: Kustomization
#metadata:
#  name: clustersecret-secrets
#  namespace: flux-system
#spec:
#  dependsOn:
#    - name: clustersecret-system
#  interval: 1h
#  retryInterval: 1m
#  timeout: 5m
#  sourceRef:
#    kind: GitRepository
#    name: flux-system
#  path: ./infrastructure/clustersecret/secrets
#  prune: true
#  decryption:
#    provider: sops
#    secretRef:
#      name: sops-age
