apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: cnpg-system
resources:
  - namespace.yml
  - helmrepository.yml
  - helmrelease.yml

configMapGenerator:
  - name: cnpg-values
    files:
      - values.yaml=values.yml
