apiVersion: kustomize.config.k8s.io/v1beta2
kind: Kustomization
metadata:
  name: tailscale
  namespace: tailscale
spec:
  decryption:
    provider: sops
    secretRef: sops-age
resources:
  - namespace.yml
  - vault-token.yml
  - helmrepository.yml
  - secretstore.yml
  - secrets.yml
