apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    external-dns.alpha.kubernetes.io/hostname: vault.kdmorris.dev
    kubernetes.io/tls-acme: "true"
  name: vault
  namespace: vault
spec:
  ingressClassName: nginx
  rules:
    - host: vault.kdmorris.dev
      http:
        paths:
        - backend:
            service:
              name: vault
              port:
                number: 8201
          path: /
          pathType: Prefix
  tls:
  - secretName: vault.kdmorris.dev
    hosts:
    - vault.kdmorris.dev
