apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: forgejo
resources:
  - ocirepository.yml

configMapGenerator:
  - name: forgejo-config
    files:
      - values.yaml=values.yml

configurations:
  - kustomizeconfig.yml
