apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: forgejo
resources:
  - namespace.yml
  - ocirepository.yml

#configMapGenerator:
#  - name: headlamp-config
#    files:
#      - values.yaml=values.yml
#
#configurations:
#  - kustomizeconfig.yml
#