apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: externaldns
  namespace: externaldns
resources:
  - namespace.yml
  - helmrepository.yml
  - secretstore.yml
  - externalsecret.yml
  - externalsecret2.yml
  - helmrelease.yml
