apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: cert-manager
  namespace: cert-manager
resources:
  - namespace.yml
  - helmrepository.yml
  - secretstore.yml
  - externalsecret.yml
  - helmrelease.yml
  - clusterissuer.yml
