---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: metallb-system
  namespace: flux-system
spec:
  interval: 1h
  retryInterval: 1m
  timeout: 5m
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./infrastructure/metallb/controller
  prune: true
  healthChecks:
  - apiVersion: apps/v1
    kind: CustomResourceDefinition
    name: L2Advertisement
    namespace: metallb
  - apiVersion: apps/v1
    kind: CustomResourceDefinition
    name: IPAddressPool
    namespace: metallb
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: metallb-configs
  namespace: flux-system
spec:
  dependsOn:
    - name: metallb-system
  interval: 1h
  retryInterval: 1m
  timeout: 5m
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./infrastructure/metallb/config
  prune: true
