apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: clustersecret-system
  namespace: flux-system
spec:
  interval: 1h
  retryInterval: 1m
  timeout: 5m
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./infrastructure/clustersecret/controller
  prune: true
#  healthChecks:
#  - apiVersion: apps/v1
#    kind: Deployment
#    name: external-secrets
#    namespace: external-secrets
#  - apiVersion: apps/v1
#    kind: Deployment
#    name: external-secrets-cert-controller
#    namespace: external-secrets
#  - apiVersion: apps/v1
#    kind: Deployment
#    name: external-secrets-webhook
#    namespace: external-secrets
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: clustersecret-secrets
  namespace: flux-system
spec:
  interval: 1h
  retryInterval: 1m
  timeout: 5m
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./infrastructure/clustersecret/secrets
  prune: true
  decryption:
    provider: sops
    secretRef:
      name: sops-age
