apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: renovate
resources:
  - helmrepository.yml
  - cronjob.yml

configMapGenerator:
  - name: renovate-values
    files:
      - values.yaml=values.yml
  - name: renovate-config
    files:
      - config-map.yaml=config-map.yml

configurations:
  - kustomizeconfig.yml
  - kustomizeconfig2.yml
