apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: renovate
resources:
  - helmrepository.yml
  - helmrelease.yml

configMapGenerator:
  - name: renovate-values
    files:
      - values.yaml=values.yml

configurations:
  - kustomizeconfig.yml
