apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: renovate
resources:
  - cronjob.yml

configMapGenerator:
  - name: renovate-config
    files:
      - config.json=config.json

configurations:
  - kustomizeconfig.yml
