apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: tailscale-secrets
  namespace: flux-system
spec:
  dependsOn:
    - name: cluster-secrets
    - name: reflector-system
  interval: 1h
  retryInterval: 1m
  timeout: 5m
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./infrastructure/tailscale/secrets
  prune: true
  healthCheckExprs:
    - apiVersion: external-secrets.io/v1beta1
      kind: ExternalSecret
      failed: status.conditions.filter(e, e.type == 'Ready').all(e, e.status == 'False')
      current: status.conditions.filter(e, e.type == 'Ready').all(e, e.status == 'True')
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: tailscale-system
  namespace: flux-system
spec:
  dependsOn:
    - name: tailscale-secrets
  interval: 1h
  retryInterval: 1m
  timeout: 5m
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./infrastructure/tailscale/controller
  prune: true
  healthChecks:
    - apiVersion: apps/v1
      kind: Deployment
      name: operator
      namespace: tailscale
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: tailscale-config
  namespace: flux-system
spec:
  dependsOn:
    - name: tailscale-system
  interval: 1h
  retryInterval: 1m
  timeout: 5m
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./infrastructure/tailscale/config
  prune: true
  healthCheckExprs:
    - apiVersion: tailscale.com/v1alpha1
      kind: ProxyClass
      failed: status.conditions.filter(e, e.type == 'Status').all(e, e.status == 'ProxyClassInvalid')
      current: status.conditions.filter(e, e.type == 'Status').all(e, e.status == 'ProxyClassValid')
