---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: openebs-system
  namespace: flux-system
spec:
  interval: 1h
  retryInterval: 1m
  timeout: 15m
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./infrastructure/openebs/controller
  prune: true
#  healthChecks:
#    - apiVersion: helm.toolkit.fluxcd.io/v2
#      kind: HelmRelease
#      name: openebs
#      namespace: openebs
#---
#apiVersion: kustomize.toolkit.fluxcd.io/v1
#kind: Kustomization
#metadata:
#  name: openebs-configs
#  namespace: flux-system
#spec:
#  dependsOn:
#    - name: openebs-system
#  interval: 1h
#  retryInterval: 1m
#  timeout: 5m
#  sourceRef:
#    kind: GitRepository
#    name: flux-system
#  path: ./infrastructure/openebs/config
#  prune: true
