apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: externaldns-secrets
  namespace: flux-system
spec:
  dependsOn:
    - name: cluster-secrets
    - name: reflector-system
  interval: 1h
  retryInterval: 1m
  timeout: 5m
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./infrastructure/externaldns/secrets
  prune: true

