apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: externaldns-secrets
  namespace: flux-system
spec:
  dependsOn:
    - name: cluster-secrets
    - name: reflector-system
  interval: 1h
  retryInterval: 1m
  timeout: 5m
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./infrastructure/externaldns/secrets
  prune: true
  healthCheckExprs:
    - apiVersion: external-secrets.io/v1beta1
      kind: ExternalSecret
      failed: status.conditions.filter(e, e.type == 'Ready').all(e, e.status == 'False')
      current: status.conditions.filter(e, e.type == 'Ready').all(e, e.status == 'True')
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: externaldns-system
  namespace: flux-system
spec:
  dependsOn:
    - name: externaldns-secrets
  interval: 1h
  retryInterval: 1m
  timeout: 5m
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./infrastructure/externaldns/controller
  prune: true

