apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: pocketid
  namespace: pocketid
spec:
  ingressClassName: cloudflare
  rules:
  - host: auth.kdmorris.dev
    http:
      paths:
      - backend:
          service:
            name: pocketid-pocket-id
            port:
              number: 80
        path: /
        pathType: ImplementationSpecific