apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: pocketid
resources:
  - namespace.yml
  - helmrepository.yml

configMapGenerator:
  - name: pocketid-config
    files:
      - values.yaml=values.yml

configurations:
  - kustomizeconfig.yml
