replicaCount: 1

host: auth.kdmorris.dev

database:
  provider: "postgres"

updateStrategy:
  type: RollingUpdate
  rollingUpdate:
    maxUnavailable: 50%
    partition: 0

backup:
  enabled: false

config:
  metricsEnabled: false
  ui:
    settings:
      app:
        appName: "Frenchie & the Geek"
        sessionDuration: 180 # minutes
      ldap:
        enabled: false

persistence:
  data:
    enabled: false