apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - metallb/kustomization.yml
  - cnpg/kustomization.yml
  - externalsecrets/kustomization.yml
  - reflector/kustomization.yml
  - secrets/kustomization.yml
  - cert-manager/kustomization.yml
