apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: cert-manager
  namespace: cert-manager
spec:
  refreshInterval: "1m"
  secretStoreRef:
    name: cert-manager
    kind: SecretStore
  target:
   name: cert-manager
  data:
    - secretKey: cloudflareApiToken
      remoteRef:
        key: cloudflareApiToken
