controller:
  podLabels:
    tailscale.com/proxy-class: "tun-access"
  admissionWebhooks:
    enabled: false
  config:
    ssl-redirect: "true"
    force-ssl-redirect: "true"
  replicaCount: 1
  service:
    labels:
      tailscale.com/proxy-class: "tun-access"
    type: LoadBalancer
    loadBalancerClass: tailscale
  ingressClassResource:
    default: false
  watchIngressWithoutClass: false
  metrics:
    enabled: false
    serviceMonitor:
      enabled: false
