apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: pocketid
resources:
  - helmrepository.yml
  - helmrelease.yml

configMapGenerator:
  - name: cloudflared-config
    files:
      - values.yaml=values.yml

configurations:
  - kustomizeconfig.yml
